controllers:
    resource: ../src/Controller/
    type: attribute

# Set route for home page
homepage:
    path: /tricks
    controller: App\Controller\HomeController::index

# Set route for user
useradim:
    path: /user
    controller: App\Controller\UserController::index