<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjE4K1y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjE4K1y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjE4K1y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjE4K1y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXjE4K1y\App_KernelDevDebugContainer([
    'container.build_hash' => 'XjE4K1y',
    'container.build_id' => 'e3286ba4',
    'container.build_time' => 1713895337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjE4K1y');
