<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDue6N9y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDue6N9y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDue6N9y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDue6N9y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDue6N9y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Due6N9y',
    'container.build_id' => '0ce2fae7',
    'container.build_time' => 1710340948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDue6N9y');
